name: Android Instant App Build

on:
  push:
    branches:
      - master  # Change this if you want builds on another branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub's Linux runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Temurin (AdoptOpenJDK)
          java-version: '17'       # Make sure to match your Gradle version

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle
        run: chmod +x android/gradlew
      
      - name: Build the Instant App
        run: |
          cd android
          set -e

          adb uninstall com.articleapp || true

          sh scripts/cleanup.bash

          ./gradlew clean

          ./gradlew appInstant:bundleRelease

          bundletool build-apks --bundle=appInstant/build/outputs/bundle/release/appInstant-release.aab  --output=local_app.apks --connected-device --ks=debug.keystore --ks-pass=pass:12345678 --ks-key-alias=key0 --key-pass=pass:12345678

          bundletool install-apks --apks local_app.apks

          adb shell am start -n com.articleapp/com.articleapp.MainActivity

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: instant-app-debug-apk
          path: android/appInstant/build/outputs/apk/debug/appInstant-debug.apk

