name: Android Build

on:
  push:
    branches: [ VideoApp ]
  pull_request:
    branches: [ VideoApp ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx4096m"
        JAVA_OPTS: "-Xmx4096m"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          node_modules
          android/.gradle
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install npm dependencies
      run: npm install

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        build-tools-version: '35.0.0'
        ndk-version: '27.1.12297006'
        cmake-version: '3.22.1'
        
    - name: Clean project
      working-directory: ./android
      run: ./gradlew clean --no-daemon
    
    - name: Build React Native bundle
      run: |
        npx react-native bundle --platform android --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res/

    - name: Build Instant App
      working-directory: ./android
      run: |
        ./gradlew clean
        ./gradlew :instantapp:assembleDebug
        ./gradlew :base:bundleDebug

    - name: Upload Instant App Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: instant-app-artifacts
        path: |
          android/instantapp/build/outputs/apk/debug/instantapp-debug.apk
          android/base/build/outputs/bundle/debug/base-debug.aab
          android/app/build/outputs/apk/debug/app-debug.apk