name: Android CI2

on:
  push:
    branches:
      - FragmentsApp
  pull_request:
    branches:
      - FragmentsApp

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      run: ./gradlew :instantapp:assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: instant-app-apk
        path: instantapp/build/outputs/apk/debug/*.apk

